language: python
sudo: false

python:
    - 3.2
    - 3.3
    - 3.4

before_install:
    - true

install:
    - pip setup.py install

before_script:
    - true

script:
    - python -m unittest discover -s ./src/activitywatch -p '*.py'
