language: python
sudo: false

python:
    - 3.3
    - 3.4

before_install:
    - true

install:
    - python setup.py install

before_script:
    - true

script:
    - python -m unittest discover -s ./tests -p '*.py'
