language: python
sudo: false

python:
    - 3.2
    - 3.3
    - 3.4

before_install:
    - ./install_dependencies.sh

install:
    - true

before_script:
    - true

script:
    - python -m unittest discover -s ./src -p '*.py'
