language: python
sudo: false

python:
    - 3.3
    - 3.4
    - nightly
# pypy3 should be enabled when it has support for Python 3.3
#   - pypy3

before_install:
    - true

install:
    - python setup.py install

before_script:
    - true

script:
    - python -m unittest discover -s ./tests -p '*.py'
